SQL_USER_NAME = 'root'
SQL_USER_PASSWORD = '*ET2016*ESEC2017*'
SQL_HOST_NAME = 'localhost'
SQL_PORT_NUMBER = '3306'
SQL_DATABASE_NAME = 'test'

SQLALCHEMY_POOL_TIMEOUT = 60
SQLALCHEMY_POOL_RECYCLE = 60
